theme = "gruvbox_dark_hard"

[editor]
bufferline = "multiple"
cursorline = true
color-modes = true
true-color = true
gutters =["diff","diagnostics", "line-numbers", "spacer"]
line-number = "absolute"
mouse = true
text-width = 79

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it


[keys.select]
"o" = "flip_selections"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[editor.cursor-shape]
insert = "bar"
